branch-defaults:
  default:
    environment: PokemonGame-env
    group_suffix: null
global:
  application_name: PokemonGame
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
